### ISSUE TITLE
hello, will it be possible to improve the accuracy by adding more layers of NN?

### ISSUE THREAD

**Issue by Yuminzhou** [SanyamSatia/strtsmrt#1]

**Comment by ssatia** [comment]
It is possible, but the computation time will increase as we add more parameters. Furthermore, there are many more factors than just news sentiment that affect stock prices, so there is a limit to how low the error can get with the current dataset.

**Comment by Yuminzhou** [comment]
ok, sure, thank you very much. I will keep exploring.

**Comment by Yuminzhou** [comment]
hello, I try to run the code "nn.py"
but it keep showing up this error:
/Users/yumin/anaconda/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
Traceback (most recent call last):
  File "nn.py", line 132, in <module>
    main()
  File "nn.py", line 130, in main
    learn(data)
  File "nn.py", line 82, in learn
    cost_function = tf.reduce_mean(tf.pow(tf.div(tf.sub(stock_price, output_layer), opening_price), 2))
AttributeError: 'module' object has no attribute 'sub'

I have installed "sub" module, but it still says I have no attribute "sub", thanks

**Comment by ssatia** [comment]
I think the problem was that I was using an older version of TensorFlow: http://stackoverflow.com/a/42218732. According to the TensorFlow 1.0.0 release notes, sub has been deprecated in favor of subtract. I have updated the code to reflect the same. Thanks for pointing that out.
